- src/components/docs/libdocs/Input.js
@tocttou 
Added the mode argument to the getImageArray documentation as per the changes made in https://github.com/Cloud-CV/cvfy-lib/pull/1
> Changed getImageArray docs

- outCalls/config.js
- package.json
- src/components/docs/gettingstarted/Configuration.js
- src/components/imports/DropboxChooser.js
- src/components/inputcomponents/ImageInput/SingleInput.js
- src/components/inputcomponents/TextImageInput/SingleInput.js
- yarn.lock
Solves #34 
Will modify to accept URLs as input in a different pull request.
> Added support for uploading images from dropbox

- .travis.yml
Added support to cache dependencies and use yarn install.
> Modified travis

- package.json
- src/components/App.js
- src/components/home/HomePage.js
- src/components/home/index.css
- src/components/index.css
- src/index.js
- yarn.lock
Added ant dependency and modified home page to use Ant components. The other pages still use a mix of material and semantic
> Introduced ant design and modified home page

- django_server/settings.py
- webpack.prod.config.js
Added webpack config to be used during production
> Webpack config for prod

- django_server/asgi.py
Created asgi file to run daphne
> Added asgi file

- .travis.yml
- api/views.py
- deployment/deploy.sh
- deployment/origami_nginx.conf
- deployment/uwsgi_params
- django_server/settings.py
Created deployment script to deploy using nginx, uwsgi and daphne.
> Deployment

- .travis.yml
- api/models.py
- deployment/deploy.sh
- django_server/settings.py
- requirements.txt
Configured to use postgres as the database
> Postgres conf

- Origami/src/components/App.js
- Origami/src/components/home/HomePage.js
- Origami/src/components/user/nonghUserProfile.js
- django_server/urls.py
Modifies mydemos page to use antd and homepage to display sider instead of the material ui navbar
> Modify MyDemo and HomePage

- Origami/src/components/user/userShareProfile.js
Changes the share profile page to use ant design
> Share profile antd

- Origami/src/components/App.js
- Origami/src/components/deployment/UsePrebuiltProject/nghDemoPage.js
- Origami/src/components/deployment/UsePrebuiltProject/registerPage.js
- Origami/src/components/inputcomponents/ImageInput/ImageSingleInput.js
- Origami/src/components/inputcomponents/index.js
- Origami/src/components/outputcomponents/ImageOutput/ImageOutputPreview.js
- Origami/src/components/sampleinput/SampleImage.js
- Origami/src/components/sampleinput/index.js
- Origami/src/components/user/userShareProfile.js
- api/admin.py
- api/models.py
- api/serializers.py
- api/views.py
- django_server/settings.py
- django_server/urls.py
Allows demo creator to add sample inputs for the demo. The user can select demos based on the number of input components present in the demo
> Sample image inputs

- Origami/src/components/App.js
- Origami/src/components/index.css
- Origami/src/components/user/nonghUserProfile.js
- Origami/src/components/user/userShareProfile.js
Fixes nav bar issues in the UI
> Fix nav bar

- .gitignore
- Origami/src/components/App.js
- Origami/src/components/deployment/UsePrebuiltProject/nghDemoFrame.js
- Origami/src/components/index.css
- Origami/src/components/inputcomponents/BaseInputComponent/TypeInput.js
- Origami/src/components/inputcomponents/ImageInput/ImageSingleInput.js
- Origami/src/components/inputcomponents/TextInput/TextSingleInput.js
- Origami/src/components/outputcomponents/AreaGraphOutput/AreaGraphOutput.js
- Origami/src/components/outputcomponents/BarGraphOutput/BarGraphOutput.js
- Origami/src/components/outputcomponents/ImageOutput/ImageOutput.js
- Origami/src/components/outputcomponents/ImageOutput/SingleOutput.js
- Origami/src/components/outputcomponents/PieChartOutput/PieChartOutput.js
- Origami/src/components/outputcomponents/ScatterGraphOutput/ScatterGraphOutput.js
- Origami/src/components/outputcomponents/TextOutput/SingleOutput.js
- Origami/src/components/outputcomponents/TextOutput/TextOutput.js
- Origami/src/components/sampleinput/SampleImage.js
- Origami/src/routes.js
- django_server/settings.py
Basic demo embedding hooks and IFrame support.
> Demo embedding

- Origami/src/components/deployment/UsePrebuiltProject/nghDemoFrame.js
- Origami/src/components/inputcomponents/BaseInputComponent/TypeInput.js
- Minor fix for passing FormData in Google Chrome.
> fix(demo-embed): Cross browser compatibility fix

- Origami/src/components/user/nonghUserProfile.js
Fixes map is not a function error
> Fix deleting demos

- .travis.yml
- README.md
- requirements.txt
Using python-coveralls, the recommended package in coveralls docs, I wrote these few lines on these files to add a coveralls badge through Travis.
> Added coveralls and coverage.

- Origami/src/components/home/HomePage.js
- package.json
- yarn.lock
Fixes: https://github.com/Cloud-CV/Origami/issues/77
Done according to this  GCI Task: https://codein.withgoogle.com/dashboard/task-instances/5821790620221440/
> Add loading screen when fetching demos in Origami

- docs/library.rst
Made new demo gists which work with updated origami-lib.
> Update demo gists

- .gitignore
- Origami/src/components/App.js
- Origami/src/components/deployment/UsePrebuiltProject/nghDemoPage.js
- Origami/src/components/home/HomePage.js
**convert inline style attributes to camelCase**
- Fixes #127 - error in javascript control regarding react inline style attributes.
- add package-lock.json to .gitignore as we use yarn as a dependency manager.
> fix(style-attributes): convert inline style attributes to camelCase Fixes #127

- api/views.py
> fixes #136

- Origami/src/components/deployment/UsePrebuiltProject/nghDemoPage.js
> fixes  #117

- Origami/src/components/App.js
- Origami/src/components/home/HomePage.js
- Origami/src/components/sampleinput/index.js
- import toastr in modules where toastr used but not imported.
- Fixes #158
> fix(158): fix toastr not imported but used issue

- Origami/src/components/deployment/UsePrebuiltProject/nghDemoFrame.js
- Fixes(#172)  Demo frame route redirects to a blank page when no input and output component is provided
> fixes #172

- Origami/src/components/deployment/UsePrebuiltProject/registerPage.js
> fixes #147

- Origami/src/components/user/userShareProfile.js
- Fix for social sharing of demo model. (#148 )
> fixes #148

- Origami/src/components/home/HomePage.js
- increase the width of search option selector to show full option name
- Fixes #149
> fix(149): fix search option selector ui.

- Origami/src/components/App.js
> styles(layout): fix main layout height

- Origami/src/components/deployment/UsePrebuiltProject/registerPage.js
- Make create demo page responsive.
- Fix footer location on register page.
- properly align register page component.
- Other minor UI tweaks.
- Fixes #139
> ui(register-page): improve create demo page UI.

- Origami/src/components/App.js
- Origami/src/components/initialSetupPage.js
- Origami/src/constants/index.js
**Description**
Fix initialSetupPage help link:
- add constants to Origami
- add read-the-docs link to Constants
- add link to Origami read the docs on initialsetup help.
- Fixes #138 
**Reviewers:**
@uttu357
> fix(initialsetup-help): fix initalSetupPage help button

- Origami/src/components/App.js
- Origami/src/components/index.css
- add an onclick handler to origami icon in app.js to take user to discover page.
- fix prettier issues with App.js
- Fixes #162
> Add origami icon click redirect to discover page.

- .gitignore
- .travis.yml
- django_server/settings.py
- package.json
- webpack-stats-local.json
- webpack.base.config.js
- webpack.local.config.js
- webpack.prod.config.js
- add frontend build to travis
- remove `webpack-stats-local.json` from origami.
- add webpack-stats-local.json to gitignore.
> fix(travis-build): add frontend build in travis and remove webpack-stats

- Origami/src/components/home/HomePage.js
- Origami/src/components/social/SocialDialog.js
- Origami/src/components/user/userShareProfile.js
- README.md
- update run webpack server command in readme
- add run tests and lint fix commands to readme for origami contributing.
> refactor(readme): include new setup instructions in readme and fix lint warnings.

- requirements.txt
- bump psycopg2 version to 2.7.4
- Fixes #202
> Upgrade psycopg2 version to 2.7.4. Fixes #202

- .github/CONTRIBUTING.md
Added Contributing Guidelines file. Thanks!!
@AvaisP
> Added Contributing Guidelines

- .github/ISSUE_TEMPLATE.md
Updated ISSUE_TEMPLATE.md with some additions!!
@AvaisP
> Updated ISSUE_TEMPLATE.md

- .github/PULL_REQUEST_TEMPLATE.md
* The Pull Request improves the PULL_REQUEST_TEMPLATE for Origami.
> Improve Origami pull request template.

- .github/CONTRIBUTING.md
> updated contribution guide

- .github/ISSUE_TEMPLATE.md
> Improve Issue Template.

- Origami/src/components/deployment/UsePrebuiltProject/registerPage.js
- Origami/src/components/user/userShareProfile.js
- README.md
> Fixes #208 :Links not working 

- README.md
Fixes #232 
- Replaced 'your' with 'you'
> Fix #232: Readme typing error

- Origami/src/components/nav_root.js
> Added route to 404 not found error for invalid URLs

- Origami/src/components/deployment/UsePrebuiltProject/registerPage.js
- Origami/src/components/stateless/task_cards.js
- Origami/src/components/user/user_github_profile.js
This PR attempts to resolve these errors in `/demo_register`.
(I'm from GCI)
```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
```
```
Invalid DOM property class. Did you mean className?
```
```
Warning: The tag <text> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
```
Now there is no console error while browsing the website at that endpoint.
> Fix errors in demo_register

- Origami/src/components/PageNotfoundHandler.js
- Origami/src/components/nav_root.js
- Origami/src/components/routes.js
- Origami/src/ui/src/containers/DefaultLayout/DefaultLayout.js
Beforehand, there was no error shown when the user navigated to an invalid URL. This makes the frontend show the default 404 error on invalid requests.
@techytushar @RishabhJain2018
Before:
After:
> Show 404 error on invalid requests

- Origami/src/components/user/user_github_profile.js
Fix #248 
Displays Correct Demo Count
On the Origami website, in the right panel, the demo count always displays 4. It does not change when a demo is created or deleted. So I have made a fix to make the demo count dependent on the number of demos create by the user. 
To do this, I have: 
- imported the function 'getDeployed'
- initialized the properties 'democount' and 'userid' in 'this.state'
- called on the provided 'getDeployed' function and then set the value of 'democount' to the length of the array being returned in the callback
- called on 'this.state.democount' to display the demo count.
_Note: I have chosen to name the property 'democount' and not 'count' in order to make the names of the variables more descriptive and create a provision against future potential conflict._ …
> Shows correct demo count

- .travis.yml
- README.md
Everything from adding steps to installing and using Postgresql to disabling Hyper-V on Windows was addressed. Be sure to check out all of the new steps that were added!
GCI Mentors: @RishabhJain2018 @erikatan
Thank you for taking the time to review my work!
> Improved installation documentation

- CommonErrors.md
In continuation with #267 .
@vpn1997 .
> Added Common Errors During Installation

- Origami/outCalls/config.js
- README.md
> Fixed typo in README.md
